### ISSUE TITLE
Won't work on latest gemini: eventData.suiteFullName not exists any more

### ISSUE THREAD

**Issue by andrey-skl** [gemini-testing/gemini-teamcity#1]
Gemini 0.11.3.
This line:  
 `return (eventData.suiteFullName.trim() + '.' +`
 throws error "Cant call method trim() of undefined", because there is no more "suiteFullName" fields. "suiteName" can be used instead

**Comment by Saulis** [comment]
Yeah, eventData.suiteFullName never officially existed. This behaviour has been based on the pull request [#131](https://github.com/gemini-testing/gemini/pull/131) I made, but has since been closed in favour of return the whole suite in events.

I need to alter the plugin to use that instead.

**Comment by andrey-skl** [comment]
Okay, thank you. It would be useful for me)

**Comment by andrey-skl** [comment]
Thanks a lot!

**Comment by Saulis** [comment]
My pleasure :-) Please let me know if you encounter any further issues.
