### ISSUE TITLE
Escape `+` sign in gemini report

### ISSUE THREAD

**Issue by Yeti-or** [gemini-testing/gemini-teamcity#12]
<img width="1280" alt="screen shot 2016-06-06 at 11 16 53" src="https://cloud.githubusercontent.com/assets/1813468/15815882/67af90c6-2bd8-11e6-8105-992c8538e914.png">

```
.../popup+header/plain/touch-phone-chrome~ref.png
=> 
.../popup%2Bheader/plain/touch-phone-chrome~ref.png
```

**Comment by sipayRT** [comment]
please, move it to `gemini` repo
