### ISSUE TITLE
Move gemini-teamcity to gemini-testing organization

### ISSUE THREAD

**Issue by sipayRT** [gemini-testing/gemini-teamcity#7]
Hi @Saulis 
Don't you want to move this plugin to gemini-testing organization? It will be much easier to maintain this package. Your owner rights will be saved.

**Comment by Saulis** [comment]
Sure, do I need some access rights for that or just use the Transfer repository feature under Settings?

**Comment by sipayRT** [comment]
Can you try to move it with Transfer repository feature?
After that I'll give you access rights to this repo from gemini-testing

**Comment by Saulis** [comment]
Yeah, looks like I need admin rights to move it.

**Comment by sipayRT** [comment]
I gave you owner rights. Try again plz

**Comment by Saulis** [comment]
:+1:

**Comment by sipayRT** [comment]
Now you're member of gemini-testing organization, but admin in this project. Can you add me to npm owner plz?

**Comment by Saulis** [comment]
Sure, what's your npm username?

**Comment by sipayRT** [comment]
the same - sipayrt ;)

**Comment by Saulis** [comment]
ok should be in order now :+1:
